/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Noby Grand (https://sketchfab.com/NobyGrand)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ghost-w-tophat-6b1217e3462440519a2d0e3e75bf16d3
Title: Ghost w/ Tophat
*/

import { useGLTF } from "@react-three/drei";
import { useEffect } from "react";
import { Mesh } from "three";

/**
 * Renders the player avatar.
 *
 * The mesh is loaded from the public folder using drei's {@link useGLTF} helper.
 * Once it is ready we traverse the scene graph and enable shadow casting so the
 * character interacts with the lighting setup.
 */
export default function GhostCharacterModel() {
  const character = useGLTF("./ghost_w_tophat.glb");

  useEffect(() => {
    character.scene.traverse((child) => {
      if (child instanceof Mesh) {
        child.castShadow = true;
      }
    });
  }, [character]);

  return (
    <primitive
      object= { character.scene }
  scale = { 0.34}
  position = { [0, -0.55, 0]}
    />
  );
}

// Preload the GLTF so it is cached before the player becomes visible.
useGLTF.preload("./ghost_w_tophat.glb");